### ISSUE TITLE
Duty Officer Issues

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora#384]
- [x] Runtime errors with Return-to-Mob and Spawn-Duty-Officer
- [x] Missing from quick rank assignment
- [x] Spawn-Duty-Officer can only be called while in a mob -- going from observer to a DO does not work. It probably should.
- [x] Roundstart logout report visable by them
- [x] Can see global LOOC feeds
- [x] Able to talk while OOC is muted
- [x] Ghosting while a DO didn't delete the mob or set a respawn delay
- [x] _Everyone_ can see the Return-to-Mob verb under Special Verbs
- [x] They can bypass ooc mute

As more crop up, modify this message and add a thing to the list up top.

**Comment by skull132** [comment]
Runtimes with the aforementioned procs:

> untime error: Cannot read null.special_role
> proc name: Return to mob (/client/verb/returntobody)
>   source file: AAlarmIndexToFlag,148
>   usr: Norman Hutchberry (/mob/dead/observer)
>   src: Hartburry (/client)
>   call stack:
> Hartburry (/client): Return to mob()

> runtime error: Cannot read null.special_role
> proc name: Spawn Duty Officer (/client/proc/spawn_duty_officer)
>   source file: AAlarmIndexToFlag,19
>   usr: Norman Hutchberry (/mob/dead/observer)
>   src: Hartburry (/client)
>   call stack:
> Hartburry (/client): Spawn Duty Officer()

> runtime error: Cannot read null.special_role
> proc name: Spawn Duty Officer (/client/proc/spawn_duty_officer)
>   source file: AAlarmIndexToFlag,19

**Comment by SoundScopes** [comment]
Runtimes were caused by people observing from the lobby since they have no mind datum

**Comment by Wittme** [comment]
Upon round start, I was subject to the roundstart logout report. not sure if leak or bug, but you may wish to investigate

**Comment by Serveris** [comment]
DOs can see global LOOC feeds.

**Comment by skull132** [comment]
Fixed in pull #398 .

Closing.
