### ISSUE TITLE
Infinite Mouse Spawn

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#393]
"Become mouse" does not possess a cooldown. This allows for a player to spam braindead mice into a room as they please.

Steps to reproduce:
1. Become mouse.
2. Ghost.
3. Become mouse.
4. Ghost.
5. Rinse and repeat.

**Comment by SoundScopes** [comment]
There is a 5 minute cooldown for mice, however this was only set when mice died

**Comment by skull132** [comment]
Fixed in pull #398 

Closing issue.
