### ISSUE TITLE
Positronic Cores Can't Use Binary

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora#400]
When spawning as a positronic brain it says:

You are a positronic brain, brought into existence on NSS Aurora.
As a synthetic intelligence, you answer to all crewmembers, as well as the AI.
Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm.
Use say :b to speak to other artificial intelligences.

You cannot however use :b to speak to artificial intelligences.

**Comment by stupidbaka** [comment]
I believe this is purposefully in order to prevent powergaming, since you can essentially create a posibrain which is not bounded by rules, who can squeal about a hacked or malf AI's plans.

**Comment by skull132** [comment]
The interesting question at this point is, should they have standard (145.9 freq) access, just in case they get forgotten about? Beyond that, the start text, as it were, can be modified easily enough.

**Comment by LordFowl** [comment]
In reply to Baka, Positronic Brains clearly /do/ have rules, since their starting text explicitly says:
"As a synthetic intelligence, you answer to all crewmembers, as well as the AI.
Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm."

**Comment by SoundScopes** [comment]
Lord I have seen Positronic Brains forgotten about or left somewhere unable to speak to anyone.
We are looking at this from an IC perspective, not from what text you get when you become one.
IC'ly there are no laws attached to Positronic Brains, they are independent CPU's.

The OOC text was setup before this was taken into consideration by other people on servers where you could squeal the AI's plans.

**Comment by skull132** [comment]
What I'm going to propose:
* Remove the OOC blurb regarding laws and binary (because they have neither)
* Hand them a radio with 145.9 freq access, so they can't get lost

Thoughts?

**Comment by LordFowl** [comment]
I was always under the impression that those blurbs weren't OoC at all, but considering you've already reached the conclusion that they are, I will settle with a 145.9 freq access being a good idea. It will keep an positronic player more in the know. (I will admit there have been rounds where I've not been forgotten necessarily, its that IC events prevented me from being socketted, such as robotics being destroyed.) A question to ask is will it function even if telecoms is down, like a station bounced radio?

If this is added, there's yet another, purely aesthetic bug. Positronic brains cannot read their own radio messages, but recieved all others normally.
Example:

HIU-144 [145.9] states: H***ie* **eyxx* ***
Is what the positronic brain's messages look like to itself.
Sarah Walk [145.9] exclaims: How dare you!
Is what other messages look like to the positron; normal.

**Comment by skull132** [comment]
Marking as an enhancement and getting to work on this.

Will see about adding the posibrains an inbuilt radio. Unsure whether I want to make it a bounced radio or a headset. The difference being in how it's activated (; shortcut or having to toggle). Both carry some positives and some negatives with them. Will see how the borgs work theirs, might use that as a basis.
