### ISSUE TITLE
pAI cannot see sign language

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora#404]
pAI devices cannot see sign language while not in a mobile chassis form. It also looks like pAI devices cannot see anything done via me in the same circumstances.

Can be duplicated by being a pAI device that is not using it's mobile chassis (I.e. held by someone, or sitting on the ground as the 'card' sprite)

**Comment by SoundScopes** [comment]
This was left as intentional due to them being a voice activated card. This was before bay added the mobile chassis.

**Comment by SierraKomodo** [comment]
Seems a bit of an odd limitation, since the universal translator module does say it can translate sign language.

**Comment by SoundScopes** [comment]
Yep that was also bay. The reasoning beind it was because the pAI's are cards that you slot into a PDA(if you wanted) or carryed around, being in a bag someone's pocket a box or somewhere would mean you can't see sigh. We also treated them as devices without cameras.

**Comment by skull132** [comment]
Then we'll adjust fire and fix the universal translator module. pAIs, generally speaking, lack eyes unless in kitty-cat-meow-meow mode (deployed). The most compliant solution, in terms of logic, would be to write a check in for the presence of the translator module and then the deployment into a form with cameras. I'll open another issue, and close this one, to redirect and refocus.
