### ISSUE TITLE
Silver Slime Core Food Isn't Filling

### ISSUE THREAD

**Issue by AliciaJewel** [Aurorastation/Aurora#418]
When you spawn food with a silver slime core, it doesn't appear to be filling the character up. Specifically, I spawned a bread slide and a Margherita slice, but when I tried to eat them, it just said "None of ______ left, oh no!" and didn't fill me up at all despite disappearing from my hand. I'm not sure if this happens with any other food.

"Head Developer PM from-Skull132: Smells like a bug. The ingredients not being added properly upon creation of the fewd container."

**Comment by skull132** [comment]
I am actually having difficulty reproducing this. Most of the food I spawned has the variables required to be consumed properly, including nutriment reagents and bites. Odd.

**Comment by skull132** [comment]
Found the potential issue. It was spawning empty food holders, so yeh. A fix is being updated in the form of 00b97c04cc596e68f15c3d9eb6e726039248d917
