### ISSUE TITLE
Character sprite does not show crossbow on back when put on backpack slot

### ISSUE THREAD

**Issue by mirkoloio** [Aurorastation/Aurora#419]
If you have a powered crossbow you can put it on your back like laser rifles. But there's no sprite for them to be seen on the Character when wearing it on the back

**Comment by Serveris** [comment]
Should be fixable with a simple item_state. Will get on this in the next couple hours.

**Comment by Zuhayr** [comment]
This was fixed on Bay, should be as easy as lifting the icon.
