### ISSUE TITLE
Slime Core Extraction Issues

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#420]
Attempting to perform 'surgery' with either the scalpel or circular saw will occasionally lead to a failed attack log on the slime, rather than cut through the slime's flesh or cut out the core itself.

**Comment by skull132** [comment]
Are you certain this isn't the result of any of the following:
* wrong step on starting up/starting a surgery in the middle?
* the slime not being on a table properly?

**Comment by OneOneThreeEight** [comment]
Slime extraction is different in that, when you stack multiple slimes upon a table, you can perform several simultaneous surgeries at one time.

However, even if you are doing slime surgery on one slime, that is properly tabled onto the Operating Table, there is still a chance for the surgery to fail and produce a missed attack log.

**Comment by skull132** [comment]
Went onto the server and did chain surgery on 7 slimes. Not a single attack-log.

Question, do you have in mind the "The scalpel/The saw passes right through slime" messages?

**Comment by OneOneThreeEight** [comment]
"The scalpel/The saw passes right through slime!"

Yes, I believe this is the issue.

**Comment by skull132** [comment]
Any item used on a slime by human-type mobs has a 25% chance of producing that result. It isn't an attack log, and it isn't a bug.
