### ISSUE TITLE
Crime Lab/Detective's Office Camera

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora#422]
Currently, if you wish to view the station's crime labs through the security cameras, you must go to, "Detective's Office."

Similarly, if you wish to see the detective's office, you must go to, "Security Dormitories Northeast."

This is a bug as a result of the old baystation map, in which the current detective's office use to be the security dormitories. Should be as simply as editting the c_tags on both cameras.

**Comment by skull132** [comment]
Map bugs on hold until pull #421 is merged.
