### ISSUE TITLE
Surgery Sleep tanks do jack-shit.

### ISSUE THREAD

**Issue by NikTheBrave** [Aurorastation/Aurora#428]
As far as I can figure out, the tanks currently cause people to go under, then immediately come out. Occasionally, sleep toxin will also fail to do anything, and they will also apparently be deaf while under, but still able to move.

Someone told me this may be caused by robotic bits, but I've seen multiple who didn't have any, and this bug has become a genuine issue.

**Comment by skull132** [comment]
How much unit of STox did you inject? 15u of STox is not a permanent knock-out. You need more than that.

Further more, did the patient have a popped lung? If so, anesthesia does not work due to the fact that it's a _gas that needs to be inhaled_.

**Comment by skull132** [comment]
This hasn't been duplicated, and the tanks are used in surgery every day. Closing issue.

**Comment by Zuhayr** [comment]
Chiming in to add that it might have been due to lung damage. N2 tanks only work if lungs are working.
