### ISSUE TITLE
Cane Sword

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora#431]
Basically, redo it to not be a box, and be an actual thing with a variable. Maybe a lock or something, so you can unsheathe it by simply clicking, instead of going through the idiotic method of taking it out of the box/container.

**Comment by OneOneThreeEight** [comment]
So, essentially a more lethal version of the infamous clickybaton?

**Comment by skull132** [comment]
I'm not sure what the connection between the two is.
