### ISSUE TITLE
The IPC Genome Project

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora#439]
IPCs, quite contrary to what you might expect, do indeed have genes, can indeed have their genes modified, and when turned into monkeys will gib violently.

It is my belief that this is obviously a bug.

In proving the first case, I gave myself both the UI and the UE of a protohuman, which 'turned' me into that protohuman (It changed my colour to purple and made my name and voice change, I'm not actually sure if it changed my IPC mechanics because of the next point)

In proving the first case, I extracted the SE of what I intended to turn into a protohuman, but accidentally left as a monkey. For a brief flash, I turned into a naked human. The flesh melted from my skin, and for a moment there was a monkey, innocently looking upon a cruel world. The monkey exploded into a heap of metallic parts, and my IPC head slowly rolled away.

I've not tested if IPCs can gain superpowers or disabilities.

**Comment by skull132** [comment]
Simplest and easiest fix: remove the ability to shove IPCs into scanners,
and to inject them with genetic material storage needles.
