### ISSUE TITLE
ID in Wallet issues

### ISSUE THREAD

**Issue by ForgottenTraveller** [Aurorastation/Aurora#440]
A month or so ago the update near where the medical scanner got the new UI the ID in wallets seemed to have broke.
- Registers as unknown on medical scanners.
- Security HUD cannot view records or set arrest status or view job icon.
- Medical HUD cannot view records or set medical status.
It occurred when the medical scanners lost the Wallet <Name>, PDA <Name> prefixes to just be the name for PDAs and UNKOWN for the wallets. Before that all of the list above was possible I believe.

**Comment by Jamini** [comment]
I'd like to take this. If only to ensure that folks with IDs in wallets also send their $job and $source properly to telecomms/the AI.

**Comment by skull132** [comment]
Should be fixed in the pull referenced above. Along with the myriad of bugfixes v.v
