### ISSUE TITLE
MOD getting attack notification when no attack is present

### ISSUE THREAD

**Issue by Aether42** [Aurorastation/Aurora#441]
I saw a character just standing in the hallway. Examination said they were asleep. I tried clicking on them, with Green "Help' intention on, to try and shake them awake. Several clicks did nothing, and I realized I was holding a briefcase in my hands. I switched hands and then got the message I was giving him a hug.

I then got PM form PM Moderator Tenenza, asking me why I was repeatedly attacking the character. I, at no point, EVER attacked this character. There was no indication of such on my end. I have a screen shot of my text output from this time. You can see from the time I examined him, to the time it said I gave him a hug (again, confirming that I had GREEN HELP INTENTION ON) no other message is present.

![image](https://cloud.githubusercontent.com/assets/11468445/6649489/40fce85c-c9b9-11e4-9ce4-3107dd6392bc.png)

**Comment by Tenenza** [comment]
Here are the vars the incident. 
![briefcase](https://cloud.githubusercontent.com/assets/11468521/6649540/7efdcaaa-c9c2-11e4-80cd-35bc132b99b2.png)

**Comment by skull132** [comment]
Tested, it's a thing with the briefcase specifically.

* The attacks do no damage
* The attacks are not displayed to anyone watching
* The attacks are not displayed to the attacker
* The attacks *are* however displayed to the admins/mods

**Comment by LordFowl** [comment]
The attacks may be displayed to the attacked; I was trying to shake someone up after a Vampire attack, and had the CSI kit as my active hand. They reported over the radio that I was attacking them, implying that they saw messages for the attack.

**Comment by SoundScopes** [comment]
Added messages
