### ISSUE TITLE
Syndicate Hardsuits are not welder protected.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#447]
I went blind today lighting up walls with thermite and a welding tool, despite having a hardsuit helmet on. It was also refitted.

thermthermthermtherm.

**Comment by GlamourChariot** [comment]
With thorough testing, I was unable to reproduce the bug in any form. It appears as though the helmet is working exactly as it should whether refitted or not.

If this crops up again, try to detail the exact specifics of when it does so, as it appears to either be an extremely circumstantial bug or merely user error.

**Comment by OneOneThreeEight** [comment]
Figured out some conditions. So, I was using thermite in a spray bottle.

Sprayed thermite on wall. Used welding tool on the thermite sprite on the wall. I get a "Your eyes begin to sting" message. I repeat this with several walls I attempt to burn down. Eventually, I go blind for a temporary amount of time. I get foggy vision for the rest of the game.

**Comment by skull132** [comment]
Okay, still, unable to replicate. Namely, I am unable to spray thermite onto a wall. And upon simply burning a wall covered with termite, I don't burn my eyes. So yeah.

**Comment by OneOneThreeEight** [comment]
Have you tried clicking the wall with the spray bottle in your active hand?

It should apply the thermite that way by spraying.

**Comment by Jamini** [comment]
Were you wearing night-vision goggles or thermals? I believe both of them negate welder protection as part of their balancing.

**Comment by OneOneThreeEight** [comment]
I was wearing thermals at the time, actually, and for sequential times I've attempted to use the welder.

I've used NVGs before but they haven't produced the same issue.

**Comment by SoundScopes** [comment]
This is an intended feature to balance the thermals, not sure if it's the same with NVG. Technically they should be because night vision and light is bright.
