### ISSUE TITLE
No image for WalkingMushrooms.

### ISSUE THREAD

**Issue by BadLemonsXI** [Aurorastation/Aurora#448]
The Walking mushrooms have a icon_living that doesn't show up for when they are placed down and become /mob/living/simple_animal/mushroom 
aka There invisible. 

The image's for it are in.[icons\mob\livestock.dmi]
but I think it should look more like [icons\obj/harvest\walkingmushroom.dmi]

Also the response_disarm doesn't work it just does response_harm.

Here's your code on the github for it. The icon_dead show's up.
/mob/living/simple_animal/mushroom
	name = "walking mushroom"
	desc = "It's a massive mushroom... with legs?"
	icon_state = "mushroom"  
	icon_living = "mushroom" 
	icon_dead = "mushroom_dead"
	small = 1
	speak_chance = 0
	turns_per_move = 1
	maxHealth = 5
	health = 5
	meat_type = /obj/item/weapon/reagent_containers/food/snacks/hugemushroomslice
	response_help  = "pets the"
	response_disarm = "gently pushes aside the"
	response_harm   = "whacks the"
	harm_intent_damage = 5

**Comment by GlamourChariot** [comment]
Implemented a fix to solve the riddle of the invisible shrooms.
