### ISSUE TITLE
IPCs have 'Cyberbrains' except when they don't.

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora#451]
So, a natural IPC body is killed. All of its organs are in place, all of its limbs attached. You remove the brain to fiddle with it, see if you can reboot it. You do organ removal surgery sans a few steps, and get an item called a "Cyberbrain". All's well.

But, if an IPC is gibbed and the head survives, when you hit it with a saw, you get a Posibrain.

In short, the process of gibbing literally transmogrifies an IPC's brain.

**Comment by Zuhayr** [comment]
Upshot of outdated organ code. Should be able to port the properly implemented organs > severed bodyparts code fairly easily unless I'm hallucinating and never managed to get it merged.

**Comment by Zuhayr** [comment]
https://github.com/Baystation12/Baystation12/blob/ae0ce4e620d53892cc6b012dbc48be2f8adfcd11/code/modules/organs/organ_external.dm#L1024

https://github.com/Baystation12/Baystation12/blob/ae0ce4e620d53892cc6b012dbc48be2f8adfcd11/code/modules/organs/organ_external.dm#L1118

**Comment by ZipZero** [comment]
An IPC, or integrated positronic chassis, has a positronic brain. The "cyberbrain" item should be replaced to reflect this.

**Comment by skull132** [comment]
I'm of mind to agree with Zip.

If we give IPCs cyberbrains, it'll turn into another run of, "Human, but..." instead of being their own, standalone thing.

**Comment by LordFowl** [comment]
I too prefer posibrain over cyberbrain.

**Comment by Zuhayr** [comment]
You're going to have to implement the posibrain as a descendant of organ code, then, or make an IPC brain standin that turns into a posibrain when src.removed() is called.

**Comment by skull132** [comment]
Will be fixed in pull #644!
