### ISSUE TITLE
Gygax weapons cannot hit any mobs.

### ISSUE THREAD

**Issue by TishinaStalker** [Aurorastation/Aurora#452]
Watched Milo Hachert try to kill animated shelves using a Gygax + Solaris Cannon + AC2. All attacks would miss. Next round, I experimented on the Odin with a carbon mob, and none of the attacks from the guns would hit the carbon mob.

**Comment by GlamourChariot** [comment]
I have created a fix for the issue of mecha weapons not being defined as having accuracy and automatically missing.
