### ISSUE TITLE
EOD Suit Incorrect Sprite

### ISSUE THREAD

**Issue by SueTheCake** [Aurorastation/Aurora#454]
The security EOD suit uses the outdated sprite, the red-colored science biosuit; it has an updated sprite in the code but the icon_states are fucked up in the file. They both have the same name.

http://puu.sh/gIVib/b5e794f068.png

**Comment by GlamourChariot** [comment]
I have removed the old sprite to ensure sec will have their shiny new suits without conflict.

**Comment by skull132** [comment]
Fixed in pull #464
