### ISSUE TITLE
Suit cooling units have a broken sprite and don't cool IPCs

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora#455]
When wearing a suit cooling unit, a sprite of a shotgun or sword (I can't tell which) is overlayed the person wearing said cooling unit.

Additionally, even when turned on, the cooling unit did not perform its function and the IPC overheated and caught fire.

**Comment by skull132** [comment]
I did some testing yesterday, and the result was that with Sec RIGs, and on back, they didn't cool. I'll do further testing, but they might not simply be meant for onback use (at that point, we'll remove the slot_back flag from them).

**Comment by mwerezak** [comment]
They were never really finished and only work when placed in suit storage. It shouldn't be hard to modify them to work when worn on the back.
