### ISSUE TITLE
Laser Tag Gun Suicide

### ISSUE THREAD

**Issue by stupidbaka** [Aurorastation/Aurora#456]
I had a rather interesting case as a CSI today, and it was the case of a cadet putting a laser tag gun in his mouth the pulling the trigger.

Logically, a toy shouldn't be used for suicide. It doesn't even show up on autopsy reports nor looking for GSR that they off themselves using a toy gun.

This is a hilarious error, but it's one that needs to be fixed.

**Comment by GlamourChariot** [comment]
I've made a fix for the practice gun not using the same safety check as the laser tag guns when attempting to suicide, no more sec recruits offing themselves.
