### ISSUE TITLE
Lungs

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora#459]
The way damaged lungs apply OXYLOSS is slightly insane and needs to be curbed. At roughly 10 points of damage, which meets the minimum bruised damage, you will basically die from being unable to breathe and constantly coughing up your blood. Keep in mind, maximum damage variable for the lungs is 30. So there is a massive disparity.

Idea is to modify the lungs so that at around 10-15 damage, they do damage to the point where it's annoying and noticeable (maybe a maximum dip of 50 OXYLOSS, before time to recover?), but not instantly incapacitating. 20-30 should be near lethal, if not lethal.

**Comment by Serveris** [comment]
Did we work out who was assigned to this in the last dev meeting?

**Comment by SoundScopes** [comment]
No it was just discussed but not assigned

**Comment by skull132** [comment]
Taking over. Proper fix created and undergoing testing at this time.

The main issue appeared to be with the damage it does: 15 per activation, with the activation being a 4% chance every tick. This is actually very, very aggressive, and makes any damage to the lung (above the bruise level) lethal, very quickly.

Currently reverting the damage done while bruised to 5 (as it was in the olden code).
Will also be testing with an additional pop of 5 damage (total of 10 per successful probability check) if the lung is actually broken.

This should make actually broken lungs more hindering, and potentially lethal, while the bruised lungs will remain an inconvenience.
