### ISSUE TITLE
Polyacid does no damage.

### ISSUE THREAD

**Issue by TishinaStalker** [Aurorastation/Aurora#463]
Earlier, a person was accidentally sprayed with polyacid. They received no damage from it. Later on, someone has polyacid squirted in their eyes, and once again no damage.

**Comment by SoundScopes** [comment]
I believe Casper tested this afterwards and said that the chemist screwed up?

**Comment by stupidbaka** [comment]
were they wearing anything covering their face?

**Comment by skull132** [comment]
Did testing right meow: even with clothing, polyacid hurts/kills after a while. So it does as advertised.
