### ISSUE TITLE
Fireaxe gets stuck on people's head without incapacitating them.

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora#476]

**Comment by skull132** [comment]
I uh. Am unsure whether this can exactly be considered a bug. The axe does a certain amount of damage, and it getting stuck does some more. If that isn't enough to force paincrit, then you will legitimately see people *cough*IPCs*cough* walking around with a fire axe in their head.

**Comment by Keinto** [comment]
I should clarify that it does not instantly paincrit them. I just lost a fight because I lost my axe by getting it stuck on their head, and they had enough time to kill me with a bat, and walk away for several more seconds.

**Comment by skull132** [comment]
Was it wielded, did they have a helmet?

**Comment by Keinto** [comment]
95% sure it was, but you can check the logs. And no, the other person did not have a helmet.

**Comment by skull132** [comment]
Yeah, that's how the mechanics work. A weapon getting stuck at an inopportune moment is something that can happen. That's how the code is built.
