### ISSUE TITLE
Energy crossbows accidentally awful

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#481]
More testing with Duck proved energy crossbows, including their traitor variants as both the concealed and RnD variants of the crossbow share the same variables, cannot reliably 2 shot KO any human-type mob. We also noted how very little damage the niche weapon even dealt. It was previously able to KO people and deal a strong amount of toxin on-hit, though I was told by Duck (as well as shown in the code somewhere) that somehow they broke.

Steps to reproduce:
1. Acquire either variant of the energy crossbow.
2. Shoot a mob.
3. Observe as the darts do nothing.

**Comment by skull132** [comment]
They do stuff now. 2 shots will stun, pretty much. So yeh, closing.
