### ISSUE TITLE
Latex gloves leave fibers?

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#485]
http://puu.sh/h296g/faf390676d.png

Self-explanatory.

**Comment by Serveris** [comment]
Somewhat. Latex bears obvious trace chemicals in the material. Enough to identify a substance as being latex. 

Would you call these traces fibers? No. I suggest you roleplay it as having some other lead to it, ie, 'We found powder commonly found on latex gloves all over the murder weapon.'

The fibers message is a blanket term for, 'This type of clothing has been rubbed all over x.'
