### ISSUE TITLE
AI's Aren't Informed of Ion Law Changes

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora#486]
Quite simply, AI's just aren't informed when their laws change due to Ion Laws. Borgs will receive a big red message telling them the new law and that their laws are updated, by AIs will receive no notification whatsoever, from my observation.

Situation: I received the law "Under no circumstance respond to any query" and my borg started asking me why I was defying my laws.

**Comment by Serveris** [comment]
Interesting. Did you begin the round as an AI, or were you assembled and installed mid round?

**Comment by LordFowl** [comment]
I began the round as an AI.

**Comment by Serveris** [comment]
Very good. I think this can be fixed by simply copying the proc over from borgs to AIs.

**Comment by ZipZero** [comment]
If this is an issue, it either only appeared very recently, or only appears in very specific circumstances. Just a few days ago, I got the mouse law as Lemon (AI), and was informed in bright red text of this law change.

**Comment by SoundScopes** [comment]
http://puu.sh/h53FU/0fd1b2435e.png

**Comment by LordFowl** [comment]
I'm going to chalk this up to my own stupidity then?

**Comment by SoundScopes** [comment]
You might have suffered a lag spike where the message was sent but the packet was lost so you didn't actually get the message to your computer.
