### ISSUE TITLE
Golem runes not working

### ISSUE THREAD

**Issue by AliciaJewel** [Aurorastation/Aurora#490]
As a ghost, standing on an adamantine golem rune does not cause it to glow. It cannot be activated to turn me into a golem. This was tested with both player-spawned and admin-spawned runes.

**Comment by Alberyk** [comment]
I am sure someone else has to use it, but we do have golems when xenobiology works for it.

**Comment by Serveris** [comment]
Valk was going this just last night. Created 3 golems no problem by use of runes.

**Comment by SoundScopes** [comment]
Added note, how long had to been a ghost for, was your original body still alive?

**Comment by Jamini** [comment]
Did you ghost out of your original body? That causes issues that can prevent ghosted cultists from being manifested, and may be related to here.
Did you suicide? Suicide can prevent spawning as well IIRC.

**Comment by skull132** [comment]
Have been unable to replicate on multiple counts, and they keep working. If this happens again, please notify an admin ingame, and reopen the issue.
