### ISSUE TITLE
IPC's Genes Can Still Be Modified

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora#492]
While IPC's have been banned from having their genes modified in conventional ways (via syringe), their genes can still be modified through radiation. This means that an IPC that is subjected to radiation  can develop superpowers.

**Comment by skull132** [comment]
Unable to replicate on current build.

**Comment by skull132** [comment]
We found one source still present: artifacts with the effect of /datum/artifact_effect/dnaswitch. So we'll be tending to that.

**Comment by skull132** [comment]
All sources of IPC gene-fuckery should now be patched. Hopefully.
