### ISSUE TITLE
Janitor's Jumpsuit doesn't have a complete "Roll Up Sleeves" option.

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora#521]
http://gyazo.com/d1d56a69a5d15be62242d2b5a0155a4e

http://gyazo.com/3b6c8f8940c59ce7e70d8cd289c2d706

http://gyazo.com/319f8e373ef4d22a9922c3a4cef1dc25

http://gyazo.com/2ecd530bdfc21b1de90276c90d36e821

While the janitor's jumpsuit updates for north and south directions, it doesn't for east or west. This is a consistency problem.

**Comment by GlamourChariot** [comment]
Updated Janitor's Jumpsuit with properly rolled up sleeves on all angles uploaded onto dropbox.

**Comment by SoundScopes** [comment]
Updated into Master on #708
