### ISSUE TITLE
ERT medic/commander/engineer rucks have no icon.

### ISSUE THREAD

**Issue by Mark9013100** [Aurorastation/Aurora#523]
So the only way to equip one is via alt+click, but even then you can't take it off.

![](http://i.imgur.com/rLKKihd.png)

**Comment by SoundScopes** [comment]
The icons got lost due to us hitting the 512 icon limit in the dmi files for some items.
I need to remember what I did with the original files.

**Comment by GlamourChariot** [comment]
Icons recovered and uploaded to dropbox for re-adding.
