### ISSUE TITLE
Detective's Office Issues

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora#541]
A couple of mapping issues with the detective's office:

The locker cannot be accessed at round start without an engineer/someone with a wrench, due to a filing cabinet blocking it off in a corner of the room. You must manually go in with a wrench, and unbolt the filing cabinet from the floor, and push it out from in front of the detective's locker. You can't reach over filing cabinets due to them having density.

The detective has no desk lamp.

The detective does not have their signature sunglasses, nor an ashtray, nor a flash (This is a big issue, as some lazier players may feel inclined to use the revolver as the go-to for self defense.)

The detective has two briefcases, each with their own rack. This seems unnecessary, and only serves to clutter up the area by a tile.

**Comment by SoundScopes** [comment]
The locker - room was redesigned on a hotfix
two briefcases, each with their own rack - If I remember right I fixed that in the hotfix
