### ISSUE TITLE
Light on pressure regulators always stays on green.

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora#551]
Pressure regulators should have a red light when the valve is unlocked but is not letting gas through, but after the map update, they always stay on green. Only way to make it red is to close the valve.

**Comment by skull132** [comment]
Not true.

When the valve is unlocked, and pressure regulation is off, then it works as a completely uninhibited open valve. As such, the light should remain green. Basically: it works as intended. The light showcases the status of the main valve, and not the status of the pressure regulation.
