### ISSUE TITLE
DO faxes going to the wrong fax machines/not appearing

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora#582]
As a duty officer, I've noticed faxxes not going to the right places.

When replying to an IAA fax, the fax appears in the bridge's fax machine.

Wehn sending a command report as a fax, the fax does /not/ appear in the bridge (As far as I can tell, it doesn't appear at all), but does get added to the communications console.

Command reports that are broadcast to the station spawn a paper as normal on the communications console.

Have not yet had a chance to test responding to faxxes sent from the bridge.

**Comment by SoundScopes** [comment]
You don't send command reports as faxes, they arrive at the communication consoles in the bridge and captains office.
All centcom faxes go to all fax machines on station.

These are all features
