### ISSUE TITLE
Crew Monitoring Computer Showing Unknown (Unknown)

### ISSUE THREAD

**Issue by obiedog** [Aurorastation/Aurora#583]
On the crew monitoring computer people are showing up as unknown (unknown) where there name should be. I am working in medical while reporting this with my sensors on full and my ID is in my PDA and I still show up on the monitor as unknown (unknown). I can tell by location that it is reporting my vitals and location. There is 9/24 players showing up this way and I noticed it was a decent chunk last round too. I am not sure if it is a bug but we can't seem to figure out what else may be going on so I figured I would report it.

Thanks! 

Update:
I was being stupid and if my ID is in my PDA and in the ID slot it does show my name. However if the ID is not in my PDA but in the ID slot alone it will not report my name. Is this intentional?

**Comment by SoundScopes** [comment]
It's a bug and we are aware of it

**Comment by obiedog** [comment]
Thank you!

PS. I just typed say "Thank you"
