### ISSUE TITLE
Visuals from AI point of view. New Sec

### ISSUE THREAD

**Issue by Xelnagahunter** [Aurorastation/Aurora#617]
I know maint tunnels aren't something AI gets to see, but other areas in the sec seems obstructed. Perhaps this is intentional, but I figured it best to let you know.

http://gyazo.com/8d6323c6927cc3a6f08ebe051ddebe40 This is the new armory. As you can see, all of the secure vault is visible, but only some of the less secure portion. An open door revealed to me that my vision doesn't end on a wall and there there is more room in that direction.

http://gyazo.com/68bdb18c98f29e31e98bce66058ad1f5 The hallway beside the vault has some obscured area. I know Maintenance is likely that way, but it;s just a space that I cannot see in a supposedly "secure" area.

http://gyazo.com/55614c497263741ea36d757c8d602525 Another of those spaces I can't see is the hallway beside the solitary confinement. This one is important so I can monitor situations at Sec's request.

http://gyazo.com/55614c497263741ea36d757c8d602525 This one, single square of "Cloaking from the AI."

http://gyazo.com/55614c497263741ea36d757c8d602525 Misisng camera in the "visitor" section of the brig.

http://gyazo.com/1e5c18a5f1efffa0b16b31fe0635aa02 Area of the crimelab that I suspect is partially obscured.

I also know that evidence lockup was unmonitored by the AI, I kinda feel it should be but whatever. I simply can't find it on this map, perhaps due to oversight on my part.

**Comment by SoundScopes** [comment]
The majority of these are in a hotfix waiting to upload
