### ISSUE TITLE
Several recipes nonfunctional

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora#626]
The recipe stated on the wiki for Tossed Salad is 2 cabbage, 1 apple, 1 carrot, 1 tomato.  Microwaving this as directed results in a burned mess.

Attempting to add a cheese wedge to a burger to create a cheeseburger also does not work.

**Comment by Jamini** [comment]
These were changed when we updated the food code. The wiki is outdated.

**Comment by Sgtsammac** [comment]
I am currently working on a new official guide for the aurora wiki, please bare with me.

**Comment by skull132** [comment]
As said, Sam is working on updating our wiki to match the foodcode we have active.
