### ISSUE TITLE
Fertilizer only functional indirectly

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora#627]
You are no longer capable of using chemicals directly from a fertilizer vial into the hydroponics trays.  You have to first put it into a bucket to apply it to any plants.  This likely applies to other things you can put on plants too.

**Comment by Jamini** [comment]
I believe this was done intentionally when fertilizer was changed from an object to a reagent.

**Comment by SoundScopes** [comment]
Use a syringe or a bucket.

**Comment by skull132** [comment]
Use a syringe, trays are now syringe or bucket based.
