### ISSUE TITLE
Cadet/Lab Assistant Other intern roles spawn nearsighted.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora#628]
Regardless of whether you have selected it as a feature of your character, all of the intern roles spawn you with prescription glasses and inset nearsightedness.

This really doesn't make much sense.

**Comment by skull132** [comment]
Tested on local build, unable to replicate.

And, this isn't how code is suppose to work. Try swapping save slots and joining as a cadet/intern, and see if it still happens again?
