### ISSUE TITLE
Stun baton

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora#629]
The stun baton in this server seems to instantly stun regardless of target's armor or physical condition.  I'm not sure why this has not been updated in this codebase to deal holloss instead of instastun, but maybe someone should get on that?

**Comment by Sgtsammac** [comment]
Or perhaps we chose not to use the Bay stun system?

**Comment by skull132** [comment]
Not a bug. Choosing to keep batons instant stun was a development decision made many months ago (whenever Bay went over the HALLOSS based system).

If you wish to potentially see it changed, you are free to raise it in the suggestions boards. There has already been one of these around recently, contributing to that suggestion may fare the best results: http://aurorastation.org/forums/viewtopic.php?f=18&t=2754
