### ISSUE TITLE
Siemen's coefficient does not function properly as it should.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#632]
I've done some testing with halloss stuff (e.g. tasers and stun projectiles) as well as armor with siemens values.

to reference for example:

/obj/item/clothing/suit/space/rig/syndi
	icon_state = "rig-syndi"
	name = "blood-red hardsuit"
	desc = "An advanced suit that protects against injuries during special operations. Property of Gorlex Marauders."
	item_state = "syndie_hardsuit"
	slowdown = 1
	w_class = 3
	armor = list(melee = 60, bullet = 50, laser = 30, energy = 15, bomb = 35, bio = 100, rad = 60)
	allowed = list(/obj/item/device/flashlight,/obj/item/weapon/tank,/obj/item/device/suit_cooling_unit,/obj/item/weapon/gun,/obj/item/ammo_magazine,/obj/item/ammo_casing,/obj/item/weapon/melee/baton,/obj/item/weapon/melee/energy/sword,/obj/item/weapon/handcuffs)
	siemens_coefficient = 0.6

As you can see, the siemens_coefficient is 0.6. This means that taser bolts (or halloss in general), upon hitting with their full impact, with only be 60% effective if they hit the arms, legs, or chest, as covered by the hardsuit. The helmet also shares these values, but anyway.

So I did some testing myself on some poor testmobs. I suited them up in the standard syndi rig gear, and then shot two taser bolts at one of them. I checked their halloss: 72 halloss, as expected. However, they still dropped to the floor unconscious, despite their vars telling me that their halloss was under 100, which is the bare minimum it takes for a mob to, after 3 seconds, drop to the floor like a limp noodle. Performed the same tests with another dummy, but without any armor at all. 2 taser bolts, same time frame. Their vars: halloss = 120.

I'm not sure what's exactly up here, the vars told me that the siemens_coefficient was indeed still working properly, but if it was as though a check wasn't being run after halloss was applied and siemens was taken into account for calculation. The taser bolts seem to go through anyway, dropping the poor sap to the floor.

That's just me speculating, anyway. Is there a reason for this, though?

**Comment by Zuhayr** [comment]
Probably deliberate considering Aurora did not merge the Bay halloss rebalance for Security.

**Comment by Zuhayr** [comment]
Can't edit on phone. See if you can repro on Baycode, if not then probably intentional.

**Comment by skull132** [comment]
Actually, not intentional. It is most likely an oversight from the merge that we had a while back, or simply an update that Baystation ran to tweak, and we didn't follow up on.

It will be something that I'll take a look at (@jamini had an idea of what it is, if I am not mistaken, something to do with agony/pain?), as yeah, siemens coefficient _is_ suppose to function as the expectation above describes.

**Comment by OneOneThreeEight** [comment]
Siemens works now, supposedly.
