### ISSUE TITLE
New Sec and the Crew Monitoring console are not up to date.

### ISSUE THREAD

**Issue by Xelnagahunter** [Aurorastation/Aurora#652]
I saw characters in the hallway being labled as in space and got curious.
http://gyazo.com/71c76a3d0a6d678078882e53f398f3c4
As you can see, I'm looking at the new sec communal brig. The map clearly shows that it's old sec. Hopefully we can get this fixed to reduce confusion for people using the Crew Monitoring consoles for the first time.

**Comment by skull132** [comment]
This is a resources issue. I'll ask @SoundScopes to have a new NanoUI map generated at some point. Or I'll do it myself, during a deader hour. Thank you for the reminder!

**Comment by skull132** [comment]
Fixed in that today's update, by Scopes. If it's not up to date then, then that's due to your local resources being out of date (you can ask an admin to reset them via an option called "Fix NanoUI" on your view variables panel).
