### ISSUE TITLE
L.W.A.P. not applying weaken, stun and stutter with armor absorption.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#671]
I'm not sure if this is intended this way, but a sniper rifle should definitely knock you on your ass even if your armor (somehow) manages to absorb the blow. That absorption is just telling you that you barely got nicked, but it shouldn't save you from suffering shock.

**Comment by SoundScopes** [comment]
Considering how deadly the sniper is and how fast you can fire it, I think it's a fair trade off. The weapon shouldn't be one click, end of the line.
