### ISSUE TITLE
Traitor item list issues

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora#673]
There are several items available on the syndicate uplink that are either redundant, or completely useless due to being unimplemented properly.

In this case, I can confirm that the 'chameleon jumpsuit' spawns you the exact same jumpsuit you already get in a chameleon kit, only it costs the same price as the whole kit.  Not work it, and leads to misconceptions that it is something different.

Additionally, the 'silent fabric' or whatever it's called, available for one telecrystal under tools, simply spawns an object called 'item' with no sprite, and no way to interact with it.

Finally, while I disagree with the removal of cryptographic sequencers's ability to hack IPCs, I guess it is your server and you can do what you want with your codebase.  However, please at least clean up your code and remove the 'you slip the sequencer into the IPC's port and short out their circuits' message, because it leads someone to believe it has actually done something, while instead they have simply alerted the IPC to the fact that they are a traitor so they can blare warnings over comms.  I recommend you replace the 'hack message' code and WHAP sound with a silent message that says something along the lines of 'that won't work', so that they can understand emagging IPCs on this server is impossible without compromising their cover.

**Comment by SoundScopes** [comment]
As a note, we never had the IPC abillity to be emagged.
I have no clue where the 'you slip the sequencer into the IPC's port and short out their circuits' comes from as we tested on the server live, the IPC didn't get any message about them holding an emag or attempted hacks. It actually gave no attack message, just the sound of a thump.
