### ISSUE TITLE
Missing scrubber pipe section outside of medical bay surgery observation room.

### ISSUE THREAD

**Issue by Doomburger** [Aurorastation/Aurora#698]
http://i.imgur.com/F4EcePM.png 

This here apparently starts off this way. Pardon the cult floor. Artificer reporting it confirmed they did not damage the pipes while converting the floor.

**Comment by LordFowl** [comment]
It must have been damaged at some point in the round, because there is a scrubber located there in Dream Maker.

**Comment by Doomburger** [comment]
That's odd, as the floor hadn't been removed before that. I'll close this, then. Thanks.

**Comment by Doomburger** [comment]
Turns out, this actually IS a bug, we've double-checked. Weird. Reopening.

**Comment by SoundScopes** [comment]
It's all to do with states, even though the state can be used in DM, the object might become corrupt at compille or runtime

**Comment by SoundScopes** [comment]
We found a load of invalid pipe states on the map, they have been replaced
