### ISSUE TITLE
Peanut Seeds have no sprite!

### ISSUE THREAD

**Issue by JoeBidenHater** [Aurorastation/Aurora#723]
I was botanist one round and I tried getting peanut seeds from the vendor, and it had no sprite and the only way I could pick it up and plant it was by right clicking it. There were also no plant sprites but the peanuts once harvested had a sprite.

**Comment by SierraKomodo** [comment]
Taking a look at this one; I think it's probably just a missing sprite or the defined sprite path is incorrect.

**Comment by SierraKomodo** [comment]
Needs a sprite labelled 'seed-peanut' in 'icons\obj\seeds.dmi'. Passed it on to Swat.
