### ISSUE TITLE
Refitted antag hardsuit helmets going invisible when light is toggled

### ISSUE THREAD

**Issue by GMR25** [Aurorastation/Aurora#731]
Emagging a suit cycler, then cycling a hardsuit to the 'bloodred hardsuit' setting will have the refitted helmet go invisible once the light is toggled.

Step-by-step to reproduce:
Step 1: E-mag any suit cycler
Step 2: Take any station hardsuit*, insert in cycler
Step 3: Set cycler to use the 'department' represented entirely by symbols ##!
Step 4: Cycle hardsuit
Step 5: Wear your new, refitted nuke op hardsuit
Step 6: Enable the helmet light
Step 7: Enjoy your invisible, bald helmet that can't be taken off without the assistance of someone else. Toggling the light again will not fix this.

*I specifically used the security hardsuit when discovering this bug.

**Comment by Alberyk** [comment]
It also can happen to regular nuke op red suits.

**Comment by skull132** [comment]
I have a feeling I know where this is going wrong. Will fix.
