### ISSUE TITLE
Atmospheric Technicians don't have access to Engie-Vends

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora#758]
I would put this under a suggestion thread, but now that they have access to engineering storage, they should be able to get meson scanners, air alarm electronics, and power cells for the scrubbers from the vendors. Please.

**Comment by Keinto** [comment]
They also have access to the Youtool next to the engie-vend, so.

**Comment by SierraKomodo** [comment]
There's two ways I can fix this, depending on how Skull/Scopes want this done.

1: I mimic what was done with the youtool machine and comment out the required access variable
2: I hunt down a required access number that opens the machine for engineers and atmos techs

**Comment by Keinto** [comment]
I think the only Engie-vend in the station is that one in engineering right? So it wouldn't be a problem to have it be all-access since people already need access to get in the room.

**Comment by SierraKomodo** [comment]
Scopes has told me this is an intended restriction.
