### ISSUE TITLE
Artificial Organs Can't Be Used? 

### ISSUE THREAD

**Issue by LetzShake** [Aurorastation/Aurora#775]
I haven't had a chance to test this on a live person yet, but at least in the case of  protohumans, if you perform normal organ removal procedures, then attempt to use a prosthetic organ on the subject, you get the message  "You can't see any useful way to use the (organ)  on (patient)"  No tools seem to work, except for ones to close up the incision and end the surgery. 

Further testing: It seems artificial limbs also do not work on catatonic patients.

**Comment by skull132** [comment]
This should be fixed and irrelevant now.
