### ISSUE TITLE
At least two Vaurcae features are broken

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora#802]
Vaurcae self heal, which is meant to be disabled.
Vaurcae have no darksight. Their darksight is meant to be better than the Tajara.
Edit: They also move just as fast as everyone else, from what I observe

Vaurcae sprites are also a bit broken. From some angles they have no neck, and weapons float when they hold them and face the side.

**Comment by skull132** [comment]
Darksight is still not fixed. The rest are.

**Comment by skull132** [comment]
Correction. Darksight is sort of fixed and functional. But the mechanic itself is really hard to keep track of. It uses really dark shades when creating shadows for the further view distance.

**Comment by skull132** [comment]
Self-healing is fixed now.
And darksight has always worked, though it may not be noticeable if your monitor brightness is too low. Use mesons to figure it out.
