### ISSUE TITLE
Wrong piping in engineering outpost.

### ISSUE THREAD

**Issue by WkSavage** [Aurorastation/Aurora#808]
There is a 3way manifold that has nothing on the one end, i was lasy and just placed a vent to fix it. 
https://gyazo.com/0525ece3d88ead4896c69ae92c07362c (before)
https://gyazo.com/484e59ca9972bea34b3b09d45ec08071 (after)

Also i think i may finally get around to PRing the airlock fixes i borrowed from baystation.

**Comment by Wittme** [comment]
Thank you for the input; the issue will be addressed
