### ISSUE TITLE
Armory shutter button don't work

### ISSUE THREAD

**Issue by Ciprian26** [Aurorastation/Aurora#818]
Armory Shutter button located in warden office don't work. Both for Warden and HoS it sais acces denied

**Comment by Serveris** [comment]
It works for the AI and synthetics. Seems to be an issue with the access requirements for pressing it.

**Comment by wksavageschool** [comment]
I fixed this on my branch. I gave the warden their own access code under access.dm (or whatever it is called) and edited the buttons to correspond with the new access.

**Comment by Wittme** [comment]
Thank you for the input; the issue will be addressed
