### ISSUE TITLE
Vaurca are able to wear hardsuits fitted for humans.

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora#822]
Seems more like an oversights, but vaurca are able to wear the regular hardsuits, while the other xenos can't do the same without using a suit cycler.

**Comment by skull132** [comment]
Weee need to think on this. Hurr.

**Comment by LordFowl** [comment]
They can also wear gloves without modification, which is a definite oversight considering Vaurca biology; each hand is comprised of two fingers and two thumbs, which to me sounds like it would fit even less in a human glove than claws.

**Comment by Alberyk** [comment]
Maybe leave them without hardsuits at all, they are already resistant to space. But allow them to wear the syndie suit like dionae.
