### ISSUE TITLE
Security Checkpoint - Broken Blastdoor Set

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora#830]
https://gyazo.com/2827465d2f5060549a546987fb9ea0dd

The fore port pair of blastdoors will not close if the button labelled 'Fore port blastdoor' is pressed. Clear-cut mapping error.

**Comment by Serveris** [comment]
http://prntscr.com/9mqh0n

Following a check on the vars, it's a minor capitalization typo between the two IDs not matching.

**Comment by Wittme** [comment]
Thank you for the input; the issue will be addressed
