### ISSUE TITLE
Cyborg radio speakers are permanently disabled when EMP'd

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora#832]
1. be borg
2. get emp'd
3. attempt to speak in department-related channels
4. unable to see your own text

**Comment by skull132** [comment]
You probably forgot to re-activate the radio's speakers. They can be accessed through this button here: ![Radio Button](http://puu.sh/mqrck/8679b53f68.png)

After testing, no matter how many times I EMP-d myself, I could start hearing my radio broadcasts again after toggling the speakers back on.
