### ISSUE TITLE
Developers appear twice in Staffwho

### ISSUE THREAD

**Issue by TishinaStalker** [Aurorastation/Aurora#843]
https://gyazo.com/a3e0eb9df8995f27b0e86a7c116fb2d8

**Comment by TishinaStalker** [comment]
Unless using it once somehow made it appear twice. I typed it in once and maybe it just gave it back to me twice? I have no idea now. It was probably my computer being stupid.

**Comment by Ryan784** [comment]
Yes, I think you somehow managed to hit it twice. As of right now the verb is working fine on my end.
