### ISSUE TITLE
Crowbarring power cells out of maglocks will delete the power cell

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora#853]
Just as it says on the tin; attempting to crowbar a power cell out of a maglock will give the message
You remove the super-capacity power cell from the magnetic door lock.

However, the power cell will not appear in a hand, or on the floor; it simply vanishes.

**Comment by skull132** [comment]
Issue only happens when the magnetic lock is held in someone's hand. At which point, powercell.loc is made to be src.loc, which happens to be the user.

Fixing now.
