### ISSUE TITLE
Strange Access Restricted. 

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora#861]
Hopefully, this is simple enough.

Step #1: Be a Security Officer
Step #2: Attempt to open the Evidence Lockup, you will notice it will not let you in.
Step #3: Attempt to open the Evidence Lockup Maintenance, it lets you in. 

Not sure if this is a bug, I leave you to figure it out. Have you had any questions, contact me in server-side or forum. I don't occasionally come onto GitHub.

**Comment by skull132** [comment]
Duplicate of #850 . Already fixed in pull request #851 . Closing.
