### ISSUE TITLE
Respawn timers constantly reset themselves

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora#886]
Not sure if this is limited to just CCIA or everyone, but my respawn timer kept resetting itself. It'd go up to about 'You have been dead for 5 minutes' then go back to 1 or 2 minutes when I checked again later.

**Comment by SierraKomodo** [comment]
Wasn't able to reproduce this in future rounds.

**Comment by skull132** [comment]
Wrong repo. If it happens again, please report it again and I'll look into how that stuff's written.
