### ISSUE TITLE
Paper Bins get stuck in backpacks

### ISSUE THREAD

**Issue by apophis775** [Aurorastation/Aurora#901]
Steps to reproduce:
1.  Drag paper-bin to yourself to pick it up
2.  Place in backpack
3.  Be unable to remove it

It used to work, it might be part of the new backpack system.  Instead of letting me drag the bin back out into my hand, it asks me to remove paper.

**Comment by Lohikar** [comment]
Wrong repository, you want: https://github.com/Aurorastation/Aurora.3
